### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by i-ky** [sunlin7/compile-db-gen#1]
I just wanted to thank you for this project. About a year ago I found myself in a situation, when I had to work on a project with an unusual build system. I tried every other `compile_commands.json` generation tools, but they all were failing to capture compiler invocations properly. Your idea of using `strace` is brilliant and worked nicely!

Some time later I decided to improve on your idea and develop `compile_commands.json` generator of my own. The main idea was to use `ptrace` directly instead or relying on parsing `strace` logs which are not meant to be machine-readable. Now it is more or less ready for use - https://github.com/i-ky/basset. I will appreciate if you give it a spin and test it in your usage scenarios to find any issues that I have missed.

**Comment by sunlin7** [comment]
Thanks for leting me know you have more improves on your `basset` project, I had read its document, and it's really a good idea to use the `ptrace` to generate the `compile_commands.json`.
I like the idea, so I stared the project. :)
Thanks
