### ISSUE TITLE
Consider passing `-z` (aka `--successful-only`) option to strace

### ISSUE THREAD

**Issue by i-ky** [sunlin7/compile-db-gen#4]
`compile-db-gen` is already picking only successful syscalls due to `= 0` in regular expressions:
https://github.com/sunlin7/compile-db-gen/blob/6a29446c898384fed35e4ebf50e2c5df28f15d02/compile-db-gen.py#L92-L93

Filtering them on strace side would reduce the amount of data `compile-db-gen` needs to parse.

**Comment by sunlin7** [comment]
I'm still working on CentOS 7, the `-z` is not avaliable in the `strace` man page.

**Comment by sunlin7** [comment]
According https://unix.stackexchange.com/questions/436074/filter-out-failed-syscalls-from-strace-log , the `-z` works for old `strace`, and I had confirmed it works on CentOS 7.
I'll add it. Thanks

**Comment by i-ky** [comment]
Please add it after #5 is merged/rejected to avoid merge conflicts, because it also touches the line where strace is invoked.
